# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import numpy as np
import matplotlib.pyplot as plt

def generate_julia_fractal(width, height, c, x_min, x_max, y_min, y_max, max_iter):
    # Create grid of complex numbers
    x = np.linspace(x_min, x_max, width)
    y = np.linspace(y_min, y_max, height)
    X, Y = np.meshgrid(x, y)
    Z = X + 1j * Y

    # Initialize output array (iteration count)
    img = np.zeros(Z.shape, dtype=int)

    # Track points that haven't escaped yet
    mask = np.ones(Z.shape, dtype=bool)

    for i in range(max_iter):
        Z[mask] = Z[mask]**2 + c
        escaped = np.abs(Z) > 2.0

        # Record iteration count at escape
        img[mask & escaped] = i
        mask[escaped] = False

        if not np.any(mask):
            break

    # Normalize to 0-1 continuous range for smoother visual output
    img = img / max_iter
    return img

# Image Resolution
width, height = 2000, 2000

# Julia constant (chosen specifically for spiraling, boundary-heavy structures)
c = complex(-0.7, 0.27015)

# Coordinate boundaries (Zoom and Center)
x_min, x_max = -0.5, 0.5
y_min, y_max = -0.5, 0.5
max_iter = 256

# Generate the fractal matrix
fractal = generate_julia_fractal(width, height, c, x_min, x_max, y_min, y_max, max_iter)

# Render and Save monochrome image
plt.figure(figsize=(10, 10), dpi=300)
plt.imshow(fractal, cmap='binary_r', extent=[x_min, x_max, y_min, y_max], origin='lower')
plt.axis('off')  # Remove axes/borders

# Save high-resolution PNG ready for garment printing
plt.savefig('tshirt_fractal_design.png', bbox_inches='tight', pad_inches=0, dpi=300)
plt.show()